# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 02:32
from __future__ import unicode_literals

from django.db import migrations


def create_groups():
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
    ]
